apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: raulcontrerasrubio/buymystuffapp-web-client
      context: web-client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.css'
        - '**/*.html'
    - image: raulcontrerasrubio/buymystuffapp-api-gateway
      context: api-gateway
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
        - '**/*.js'
        - '**/*.css'
        - '**/*.html'
deploy:
  kubectl:
    manifests:
      - k8s/web-client-config.yml
      - k8s/api-gateway-config.yml