apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: raulcontrerasrubio@gmail.com
    privateKeySecretRef:
      name: issuer-prod
    solvers:
      - http01:
          ingress:
            class: nginx
