apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: buymystuffapp-com-tls
spec:
  secretName: buymystuffapp-com
  issuerRef:
    name: issuer-prod
    kind: ClusterIssuer
  commonName: buymystuffapp.com
  dnsNames:
    - buymystuffapp.com
    - www.buymystuffapp.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - buymystuffapp.com
          - www.buymystuffapp.com